const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=require('node:path').resolve(__dirname,'..');
const C=require(base+'/assets/core.js');
const bank=JSON.parse(fs.readFileSync(base+'/data/banco.json','utf8'));
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('205 IDs únicos y 178 preguntas activas',()=>{assert.equal(bank.questions.length,205);assert.equal(new Set(bank.questions.map(q=>q.id)).size,205);assert.equal(bank.questions.filter(q=>q.status==='active').length,178);C.validateQuestions(bank.questions);});
test('Las claves permanecen correctas al reordenar opciones',()=>{for(const q of bank.questions.filter(q=>q.status!=='pending'&&q.options.length)){for(let n=0;n<15;n++){const order=C.shuffle(q.options.map((_,i)=>i));const chosen=order.filter(i=>q.correct.includes(i));assert(C.grade(q.correct,chosen));assert.equal(q.answer,q.correct.map(i=>q.options[i]).join(' · '),q.id);}}});
test('Selección múltiple exige conjunto completo sin extras',()=>{assert(C.grade([0,2],[2,0]));assert(!C.grade([0,2],[0]));assert(!C.grade([0,2],[0,1,2]));});
test('Intervalos, errores y avance de dificultad',()=>{const now=10000;let p=C.schedule({},'again',now);assert.equal(p.due,now+600000);assert.equal(p.streak,0);p=C.schedule(p,'good',now);assert.equal(p.interval,1);p=C.schedule(p,'good',now);assert.equal(p.interval,3);p=C.schedule(p,'good',now);assert.equal(p.interval,7);assert(C.mastered(p));p=C.schedule(p,'again',now);assert(!C.mastered(p));assert.equal(p.interval,0);});
test('CSV preserva comas, comillas y saltos de línea',()=>{const q={id:'TEST-01',module:'teoria',week:1,stem:'Una pregunta, con coma\ny "comillas"',type:'single',options:['A','B'],correct:[1],explanation:'Explicación'};const keys=Object.keys(q),csv=keys.join(',')+'\n'+keys.map(k=>'"'+String(Array.isArray(q[k])?JSON.stringify(q[k]):q[k]).replaceAll('"','""')+'"').join(',');assert.equal(C.validateQuestions(C.csvParse(csv))[0].stem,q.stem);});
test('Importación inválida rechazada antes de mutar',()=>{const q=bank.questions[0];assert.throws(()=>C.validateQuestions([{...q,correct:[999]}]));assert.throws(()=>C.validateQuestions([{...q,id:'__proto__'}]));assert.throws(()=>C.validateQuestions([{...q,explanation:''}]));assert.throws(()=>C.validateQuestions([q,q]));});
test('Respaldo conserva progreso y notas sin restaurar sesiones',()=>{const s=C.fresh();s.reviews.TEST=C.schedule({},'good');s.notes['week-1']='Mi nota';s.history=[{id:'TEST',at:Date.now(),correct:true,objective:true}];s.session={incomplete:true};const restored=C.restoreBackup({app:'genetica-urp',version:1,state:s});assert.equal(restored.history.length,1);assert.equal(restored.notes['week-1'],'Mi nota');assert.equal(restored.session,null);});
// A controlled DOM adapter exercises complete view/render and user-action handlers.
// This is a logic/integration check, not a visual browser test.
const events={},windowEvents={},nodes=new Map(),store=new Map();let intervalId=0;
function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',open:false,dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},focus(){},setSelectionRange(){},scrollIntoView(){},addEventListener(){}});return nodes.get(selector);}
const doc={querySelector:node,querySelectorAll:()=>[],addEventListener:(name,fn)=>events[name]=fn,createElement:()=>({click(){},remove(){}}),body:{append(){}}};
const context={window:null,document:doc,location:{hash:'#inicio',protocol:'file:'},navigator:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},console,Intl,Date,Math,Map,Set,JSON,Array,Object,Number,String,RegExp,Error,URL,Blob,FormData,AbortController,setTimeout:()=>++intervalId,clearTimeout(){},setInterval:()=>++intervalId,clearInterval(){}};
context.window=context;context.addEventListener=(name,fn)=>windowEvents[name]=fn;context.scrollTo=()=>{};vm.createContext(context);
vm.runInContext(fs.readFileSync(base+'/data/bank.js','utf8'),context);vm.runInContext(fs.readFileSync(base+'/assets/core.js','utf8'),context);vm.runInContext(fs.readFileSync(base+'/assets/app.js','utf8'),context);
const click=(action,dataset={})=>events.click({target:{closest:()=>({dataset:{action,...dataset},disabled:false,classList:{toggle(){}},setAttribute(){}})}});
const go=hash=>{context.location.hash='#'+hash;windowEvents.hashchange();};
const getState=()=>JSON.parse(store.get(C.KEY)||JSON.stringify(C.fresh()));
test('Todas las vistas se renderizan sin errores de ejecución',()=>{for(const route of ['inicio','teoria','laboratorio','ruta','progreso','banco','biblioteca','practica']){go(route);assert(node('#main').innerHTML.length>100,route);}});
test('Laboratorio recalcula cruces y CNV; mini caso responde',()=>{go('laboratorio');click('lab-tab',{tab:'tools'});assert(node('#main').innerHTML.includes('25%'));events.change({target:{dataset:{punnett:'a'},value:'AA'}});assert(node('#tool-panel').innerHTML.includes('0%'));click('tool',{tool:'cnv'});assert(node('#main').innerHTML.includes('Pérdida de una copia'));events.change({target:{dataset:{cnv:'copies'},value:'3'}});assert(node('#tool-panel').innerHTML.includes('Ganancia de una copia'));click('tool',{tool:'challenge'});click('challenge-select',{index:'1'});click('challenge-check');assert(node('#main').innerHTML.includes('Bien razonado.'));});
test('Práctica objetiva persiste, califica y programa una sola vez',()=>{go('banco');click('open-question',{id:'S1-01'});go('practica');let s=getState().session;click('select-answer',{index:String(s.items[0].q.correct[0])});click('check-answer');assert(node('#main').innerHTML.includes('Correcto. Conecta'));click('rate',{rating:'good'});assert.equal(getState().history.length,1);assert.equal(getState().reviews['S1-01'].interval,1);assert(getState().session.complete);assert(node('#main').innerHTML.includes('20.0'));click('rate',{rating:'good'});assert.equal(getState().history.length,1);});
test('Respuesta abierta no suma una nota objetiva',()=>{click('open-question',{id:'LAB1-Q09'});go('practica');node('#own-answer').value='Autosómica recesiva';click('check-answer');click('rate',{rating:'good'});const last=getState().history.at(-1);assert.equal(last.objective,false);assert.equal(last.correct,true);assert(node('#main').innerHTML.includes('autoevaluaciones, fuera de la nota'));});
test('Pregunta pendiente muestra revisión sin iniciar sesión',()=>{const id=getState().session.id;click('open-question',{id:'PIZ-L10'});assert(node('#modal').innerHTML.includes('No participa en tu nota'));assert.equal(getState().session.id,id);});
test('Simulacro oculta la clave y cuenta sin contestar al terminar',()=>{go('inicio');click('exam-config');node('#exam-module').value='teoria';node('#exam-week').value='1';node('#exam-count').value='10';node('#exam-minutes').value='10';click('start-exam');go('practica');let s=getState().session;assert.equal(s.items.length,10);assert(!node('#main').innerHTML.includes('Respuesta modelo'));click('select-answer',{index:String(s.items[0].q.correct[0])});click('check-answer');s=getState().session;assert.equal(s.answers.length,1);assert.equal(s.index,1);assert(!node('#main').innerHTML.includes('Correcto. Conecta'));click('finish-exam');s=getState().session;assert.equal(s.answers.filter(a=>a.correct).length,1);assert.equal(s.answers.filter(a=>a.unanswered).length,9);assert(node('#main').innerHTML.includes('2.0'));});
test('Errores y favoritos filtran sin incluir pendientes',()=>{go('banco');click('bank-tab',{tab:'browse'});events.change({target:{dataset:{filter:'state'},value:'errors'}});assert(node('#main').innerHTML.includes('9 resultados'));click('bookmark',{id:'S1-01'});events.change({target:{dataset:{filter:'state'},value:'saved'}});assert(node('#main').innerHTML.includes('1 resultados'));});
test('Plan y apuntes se guardan',()=>{go('ruta');events.change({target:{dataset:{day:'1'},checked:true}});assert(getState().planDone.includes(1));go('biblioteca');events.change({target:{dataset:{note:'week-1'},value:'Distinguir STOP de frameshift'}});assert.equal(getState().notes['week-1'],'Distinguir STOP de frameshift');});
console.log(`\n${count} comprobaciones superadas. La revisión visual de navegador no está incluida.`);
